//GSM小区话务业务量
<select id="tableChooseSE">    
     <if test=" '@timeType'=='month' ">IPMSDM.DM_RE_2G_CELL_HW_BUSINESS_M</if>
     <if test=" '@timeType'=='hour' ">IPMSDM.DM_RE_2G_CELL_HW_BUSINESS_H</if>
     <if test=" '@timeType'=='day' ">IPMSDM.DM_RE_2G_CELL_HW_BUSINESS_D</if>   
</select>


<select id="resultMapping">
 --TIME_ID=时间 --CELL_NAME=小区名称 --ATTNBRSDCCH=SDCCH试呼次数 --OVLFNBRSDCCH=SDCCH溢出次数 --FAILNBRSDCCHASSIGN=SDCCH分配失败总次数 --DROPNBRSDCCH=SDCCH掉话总次数 --SDCCHSMSTRAF=SDCCH总话务量 --AVAILNBRTCH=TCH可用总数 --ATTNBRTCHNHO=TCH试呼总次数(不含切换) --OVFLNBRTCHNHO=话音信道溢出总次数（不含切换） --FAILNBRTCHASSNHO=TCH分配失败总次数（不含切换） --NOSUCCNBRTCHASSNHO=TCH分配不成功总次数（不含切换） --ATTNBRTCH=TCH试呼总次数(含切换) --OVFLNBRTCH=TCH溢出总次数（含切换） --FAILASSNBRTCH=TCH分配失败总次数（含切换） --NOSUCCASSNBRTCH=TCH分配不成功总次数（含切换） --SEIZENBRTCHNHO=TCH占用总次数（不含切换） --SEIZENBRTCH=TCH占用总次数（含切换） --DROPNBRTCH=TCH掉话总次数 --TCHTRAF=TCH总话务量 --GSMBYTES=GSM流量(MB) --PDCHULBYTES=PDCH上行数据流量（单位:MB） --PDCHDLBYTES=PDCH下行数据流量（单位:MB） --EGPRSDLBYTES=EGPRS下行RLC层流量（单位:MB） --EGPRSULBYTES=EGPRS上行RLC层流量（单位:MB） --ATTNBRHANDOVER=切换请求总次数 --SUCCNBRHANDOVER=切换成功总次数 --SEIZEDNBRSDCCH=SDCCH分配总次数 --SESNBRSDCCH=SDCCH占用总次数 --WIRE_CONN_RATIO=无线接通率(%) --WIRE_INSERT_RATIO=无线接入性 --OVFL_VOICE_RATIO=话音溢出率(%) --OVFL_SIGN_RATIO=信令溢出率(%) --SW_SUCC_RATIO=切换成功率(%) --DROP_RATIO=掉话率(%) --SDCCH_DISTRIBUTE_SUCC_RATIO=SDCCH分配成功率(%) --TCH_DISTRIBUTE_SUCC_RATIO=TCH分配成功率(%) --WIRE_DROP_RATIO=无线掉话率(%) --TCHHALFTRAF=半速率话务量 --TCHHALFTRAF_RATIO=半速率话务量占用比例(%) --AVAILNBRDLTBF=下行平均并发TBF数 --AVAILSEIZENBRPDCH=占用的PDCH的平均数目(含EGPRS和GPRS) --PDCH_REUSABILITY=PDCH复用度 --VOICE_CHANNEL_CNT=语音信道数 --STATIC_CHANNEL_CNT=静态数据信道数 --WIRE_USE_RATIO=无线利用率(%)
</select>

select 
TIME_ID,
CELL_NAME,
ATTNBRSDCCH,
OVLFNBRSDCCH,
FAILNBRSDCCHASSIGN,
DROPNBRSDCCH,
SDCCHSMSTRAF,
AVAILNBRTCH,
ATTNBRTCHNHO,
OVFLNBRTCHNHO,
FAILNBRTCHASSNHO,
NOSUCCNBRTCHASSNHO,
ATTNBRTCH,
OVFLNBRTCH,
FAILASSNBRTCH,
NOSUCCASSNBRTCH,
SEIZENBRTCHNHO,
SEIZENBRTCH,
round(DROPNBRTCH,2) DROPNBRTCH,
round(TCHTRAF,2) TCHTRAF,
round(GSMBYTES,2) GSMBYTES,
round(PDCHULBYTES,2) PDCHULBYTES,
round(PDCHDLBYTES,2) PDCHDLBYTES,
round(EGPRSDLBYTES,2) EGPRSDLBYTES,
round(EGPRSULBYTES,2) EGPRSULBYTES,
ATTNBRHANDOVER,
SUCCNBRHANDOVER,
SEIZEDNBRSDCCH,
SESNBRSDCCH,
WIRE_CONN_RATIO,
WIRE_INSERT_RATIO,
OVFL_VOICE_RATIO,
OVFL_SIGN_RATIO,
SW_SUCC_RATIO,
DROP_RATIO,
SDCCH_DISTRIBUTE_SUCC_RATIO,
TCH_DISTRIBUTE_SUCC_RATIO,
WIRE_DROP_RATIO,
round(TCHHALFTRAF,2) TCHHALFTRAF,
TCHHALFTRAF_RATIO,
round(AVAILNBRDLTBF,2) AVAILNBRDLTBF,
round(AVAILSEIZENBRPDCH,2) AVAILSEIZENBRPDCH,
PDCH_REUSABILITY,
VOICE_CHANNEL_CNT,
STATIC_CHANNEL_CNT,
WIRE_USE_RATIO
from <included id="tableChooseSE"/> where 1=1
<if test=" '@isContinue'=='t' ">
    and TIME_ID between to_number(#startTime#) and to_number(#endTime#)
</if>
<if test=" '@isContinue'=='f' ">
    and to_char(TIME_ID) in (#discteteTime#)
</if> 
<jdbcType name="discteteTime" type="array-char"/>

//TD小区话务业务量
<select id="tableChooseSE">    
     <if test=" '@timeType'=='month' ">IPMSDM.DM_RE_3G_CELL_HW_BUSINESS_M</if>
     <if test=" '@timeType'=='hour' ">IPMSDM.DM_RE_3G_CELL_HW_BUSINESS_H</if>
     <if test=" '@timeType'=='day' ">IPMSDM.DM_RE_3G_CELL_HW_BUSINESS_D</if>   
</select>


<select id="resultMapping">
 --TIME_ID=时间 --CELL_NAME=小区名称 --SUCCCONNESTAB_1=CS域RRC建立成功次数（业务相关） --ATTCONNESTAB_1=CS域RRC建立尝试次数（业务相关） --SUCCESTABCSPERCELL=CS域RAB建立成功的RAB数目 --ATTESTABCSPERCELL=CS域RAB建立请求的RAB数目 --CS_WIRE_CONN_RATIO=CS域无线接通率(%) --SUCCESTABCSPERCELL_CONV_2_2=语音业务RAB建立成功的RAB数目 --ATTESTABCSPERCELL_CONV_2_2=语音业务RAB建立请求的RAB数目 --SUCCESTABCSPERCELL_2_2_RATIO=语音业务RAB建立成功率(%) --AMR_WIRE_CONN_RATIO=AMR(语音)业务无线接通率(%) --SUCCESTABCSPERCELL_CONV_5_5=视频电话业务RAB建立成功的RAB数目 --ATTESTABCSPERCELL_CONV_5_5=视频电话业务RAB建立请求的RAB数目 --VP_WIRE_CONN_RATIO=视频电视(VP)无线接通率(%) --SUCCCONNESTAB=PS域RRC建立成功次数（业务相关） --ATTCONNESTAB=PS域RRC建立尝试次数（业务相关） --SUCCESTABPSPERCELL=PS域RAB建立成功的RAB数目 --ATTESTABPSPERCELL=PS域RAB建立请求的RAB数目 --PS_WIRE_CONN_RATIO=PS域无线接通率(%) --RELREQCSPERCELL=RNC请求释放的电路域RAB数目 --CS_WIRE_DROP_RATIO=CS域无线掉话率(%) --RELREQCSPERCELL_CONV=RNC请求释放的语音业务RAB总数目 --SUCCESTABCSPERCELL_CONV=语音业务RAB建立成功的RAB 数目 --AMR_WIRE_DROP_RATIO=AMR(语音)业务无线掉话率(%) --RELREQCSPERCELL_CONV_5_5=RNC请求释放的视频电话业务RAB 总数目 --VP_WIRE_DROP_RATIO=视频电视(VP)无线掉话率(%) --RELREQPSPERCELL=RNC请求释放的PS域RAB总数目 --PS_WIRE_DROP_RATIO=PS域无线掉线率(%) --VOICE_TRAFFIC=语音话务量 --VIDEO_TRAFFIC=视频话务量 --PSULOCT=Ps域上行流量(MB) --PSDLOCT=Ps域下行流量(MB) --PSOCT=PS域总流量(MB) --NBR_AVAILBRUUL=配置的上行BRU数 --NBR_AVAILBRUDL=配置的下行BRU数 --MEAN_NBR_ASSNBRUUL=上行平均占用的BRU数 --MEAN_NBR_ASSNBRUDL=下行平均占用的BRU数 --TD_NETWORK_USE_RATIO=TD网络利用率(%)
</select>

select 
TIME_ID,
CELL_NAME,
SUCCCONNESTAB_1,
ATTCONNESTAB_1,
SUCCESTABCSPERCELL,
ATTESTABCSPERCELL,
CS_WIRE_CONN_RATIO,
SUCCESTABCSPERCELL_CONV_2_2,
ATTESTABCSPERCELL_CONV_2_2,
SUCCESTABCSPERCELL_2_2_RATIO,
AMR_WIRE_CONN_RATIO,
SUCCESTABCSPERCELL_CONV_5_5,
ATTESTABCSPERCELL_CONV_5_5,
VP_WIRE_CONN_RATIO,
SUCCCONNESTAB,
ATTCONNESTAB,
SUCCESTABPSPERCELL,
ATTESTABPSPERCELL,
PS_WIRE_CONN_RATIO,
RELREQCSPERCELL,
CS_WIRE_DROP_RATIO,
RELREQCSPERCELL_CONV,
SUCCESTABCSPERCELL_CONV,
AMR_WIRE_DROP_RATIO,
RELREQCSPERCELL_CONV_5_5,
VP_WIRE_DROP_RATIO,
RELREQPSPERCELL,
PS_WIRE_DROP_RATIO,
round(VOICE_TRAFFIC,2) VOICE_TRAFFIC,
round(VIDEO_TRAFFIC,2) VIDEO_TRAFFIC,
round(PSULOCT,2) PSULOCT,
round(PSDLOCT,2) PSDLOCT,
round(PSOCT,2) PSOCT,
NBR_AVAILBRUUL,
NBR_AVAILBRUDL,
round(MEAN_NBR_ASSNBRUUL,2) MEAN_NBR_ASSNBRUUL,
round(MEAN_NBR_ASSNBRUDL,2) MEAN_NBR_ASSNBRUDL,
TD_NETWORK_USE_RATIO
from <included id="tableChooseSE"/> where 1=1
<if test=" '@isContinue'=='t' ">
    and TIME_ID between to_number(#startTime#) and to_number(#endTime#)
</if>
<if test=" '@isContinue'=='f' ">
    and to_char(TIME_ID) in (#discteteTime#)
</if> 
<jdbcType name="discteteTime" type="array-char"/>

//LTE小区话务业务量
<select id="tableChooseSE">    
     <if test=" '@timeType'=='month' ">IPMSDM.DM_RE_4G_CELL_HW_BUSINESS_M</if>
     <if test=" '@timeType'=='hour' ">IPMSDM.DM_RE_4G_CELL_HW_BUSINESS_H</if>
     <if test=" '@timeType'=='day' ">IPMSDM.DM_RE_4G_CELL_HW_BUSINESS_D</if>   
</select>


<select id="resultMapping">
 --TIME_ID=时间 --CELL_NAME=小区名称 --UPOCTUL=上行流量(MB) --UPOCTDL=下行流量(MB) --UPOCT=上下行总流量(MB) --ATTCONNESTAB=RRC连接建立请求次数 --RRC连接建立请求次数 --SUCCCONNESTAB=RRC连接建立成功次数 --RRC_CONN_SUCC_RATIO=RRC连接建立成功率(%) --NBRATTESTAB=E-RAB建立请求数 --NBRSUCCESTAB=E-RAB建立成功数 --ERAB_ESTAB_SUCC_RATIO=E-RAB建立成功率(%) --WIRE_CONN_RATIO=无线接通率(%) --ATTRELENB=eNB请求释放上下文数 --ATTRELENBNORMAL=正常的eNB请求释放上下文数 --SUCCINITALSETUP=初始上下文建立成功次数 --NBRLEFT_CONTEXT=遗留上下文个数 --WIRE_DROP_RATIO=无线掉线率(%) --NBRREQRELENB=eNB请求释放的E-RAB数 --NBRREQRELENB_NORMAL=正常的eNB请求释放的E-RAB数 --HOFAIL=切出失败的E-RAB数 --NBRLEFT=遗留E-RAB个数 --NBRHOINC=切换入E-RAB数 --ERAB_DROP_RATIO_CL=E-RAB掉线率（小区级）(%) --ERAB_DROP_RATIO=E-RAB掉线率(%) --ATTPREPINC=eNB间切换入请求次数 --SUCCPREPINC=eNB间切换入准备成功次数 --ENB_INTER_SW_IN_PRE_SUCC_RATIO=eNB间切换入准备成功率(%) --ATTOUTINTERENBS1=eNB间S1切换出请求次数 --SUCCOUTINTERENBS1=eNB间S1切换出成功次数 --ENB_INTER_S1_SW_SUCC_RATIO=eNB间S1切换成功率(%) --ATTOUTINTERENBX2=eNB间X2切换出请求次数 --SUCCOUTINTERENBX2=eNB间X2切换出成功次数 --ENB_INTER_X2_SW_SUCC_RATIO=eNB间X2切换成功率(%) --ENB_INTER_SW_SUCC_RATIO=eNB间切换成功率(%) --ATTOUTINTRAENB=eNB内切换出请求次数 --SUCCOUTINTRAENB=eNB内切换出成功次数 --ENB_INTRA_SW_SUCC_RATIO=eNB内切换成功率(%) --SW_SUCC_RATIO=切换成功率(%) --PRBTOTUL=上行PUSCH PRB占用平均数 --PUSCHPRBMEANTOT=上行PUSCH PRB可用平均数 --PRBTOTDL=下行PDSCH PRB占用平均数 --PDSCHPRBMEANTOT=下行PDSCH PRB可用平均数 --MEAN_PRB_UL_UTIL_RATIO=上行PRB平均利用率(%) --MEAN_PRB_DL_UTIL_RATIO=下行PRB平均利用率(%) --PDCCHCCEUTILRATIO=PDCCH信道CCE占用率(%) --CONNMEAN=RRC连接平均数 --CONNMAX=RRC连接最大数 --EFFECTIVECONNMEAN=有效RRC连接平均数 --EFFECTIVECONNMAX=有效RRC连接最大数
</select>

select 
TIME_ID,
CELL_NAME,
round(UPOCTUL,2) UPOCTUL,
round(UPOCTDL,2) UPOCTDL,
round(UPOCT,2) UPOCT,
ATTCONNESTAB,
SUCCCONNESTAB,
round(RRC_CONN_SUCC_RATIO,2) RRC_CONN_SUCC_RATIO,
NBRATTESTAB,
NBRSUCCESTAB,
round(ERAB_ESTAB_SUCC_RATIO,2) ERAB_ESTAB_SUCC_RATIO,
round(WIRE_CONN_RATIO,2) WIRE_CONN_RATIO,
ATTRELENB,
ATTRELENBNORMAL,
SUCCINITALSETUP,
NBRLEFT_CONTEXT,
round(WIRE_DROP_RATIO,2) WIRE_DROP_RATIO,
NBRREQRELENB,
NBRREQRELENB_NORMAL,
HOFAIL,
NBRLEFT,
NBRHOINC,
round(ERAB_DROP_RATIO_CL,2) ERAB_DROP_RATIO_CL,
round(ERAB_DROP_RATIO,2) ERAB_DROP_RATIO,
ATTPREPINC,
SUCCPREPINC,
round(ENB_INTER_SW_IN_PRE_SUCC_RATIO,2) ENB_INTER_SW_IN_PRE_SUCC_RATIO,
ATTOUTINTERENBS1,
SUCCOUTINTERENBS1,
round(ENB_INTER_S1_SW_SUCC_RATIO,2) ENB_INTER_S1_SW_SUCC_RATIO,
ATTOUTINTERENBX2,
SUCCOUTINTERENBX2,
round(ENB_INTER_X2_SW_SUCC_RATIO,2) ENB_INTER_X2_SW_SUCC_RATIO,
round(ENB_INTER_SW_SUCC_RATIO,2) ENB_INTER_SW_SUCC_RATIO,
ATTOUTINTRAENB,
SUCCOUTINTRAENB,
round(ENB_INTRA_SW_SUCC_RATIO,2) ENB_INTRA_SW_SUCC_RATIO,
round(SW_SUCC_RATIO,2) SW_SUCC_RATIO,
round(PRBTOTUL,2) PRBTOTUL,
round(PUSCHPRBMEANTOT,2) PUSCHPRBMEANTOT,
round(PRBTOTDL,2) PRBTOTDL,
round(PDSCHPRBMEANTOT,2) PDSCHPRBMEANTOT,
round(MEAN_PRB_UL_UTIL_RATIO,2) MEAN_PRB_UL_UTIL_RATIO,
round(MEAN_PRB_DL_UTIL_RATIO,2) MEAN_PRB_DL_UTIL_RATIO,
round(PDCCHCCEUTILRATIO,2) PDCCHCCEUTILRATIO,
round(CONNMEAN,2) CONNMEAN,
CONNMAX,
round(EFFECTIVECONNMEAN,2) EFFECTIVECONNMEAN,
EFFECTIVECONNMAX
from <included id="tableChooseSE"/> where 1=1
<if test=" '@isContinue'=='t' ">
    and TIME_ID between to_number(#startTime#) and to_number(#endTime#)
</if>
<if test=" '@isContinue'=='f' ">
    and to_char(TIME_ID) in (#discteteTime#)
</if> 
<jdbcType name="discteteTime" type="array-char"/>


//GSM小区话务利用率
<select id="tableChooseSE">    
     <if test=" '@timeType'=='month' ">IPMSDM.DM_RE_2G_CELL_HW_UTILITY_M</if>
     <if test=" '@timeType'=='hour' ">IPMSDM.DM_RE_2G_CELL_HW_BUSINESS_H</if>
     <if test=" '@timeType'=='day' ">IPMSDM.DM_RE_2G_CELL_HW_UTILITY_D</if>   
</select>


<select id="resultMapping">
 --TIME_ID=时间 --CELL_NAME=小区名称 --BUSY_TIME=忙时时间点 --VOICE_TRAF=语音话务量(ERL) --ATTNBRSDCCH=SDCCH试呼次数 --OVLFNBRSDCCH=SDCCH溢出次数 --FAILNBRSDCCHASSIGN=SDCCH分配失败总次数 --DROPNBRSDCCH=SDCCH掉话总次数 --SDCCHSMSTRAF=SDCCH总话务量 --AVAILNBRTCH=TCH可用总数 --ATTNBRTCHNHO=TCH试呼总次数(不含切换) --OVFLNBRTCHNHO=话音信道溢出总次数（不含切换） --FAILNBRTCHASSNHO=TCH分配失败总次数（不含切换） --NOSUCCNBRTCHASSNHO=TCH分配不成功总次数（不含切换） --ATTNBRTCH=TCH试呼总次数(含切换) --OVFLNBRTCH=TCH溢出总次数（含切换） --FAILASSNBRTCH=TCH分配失败总次数（含切换） --NOSUCCASSNBRTCH=TCH分配不成功总次数（含切换） --SEIZENBRTCHNHO=TCH占用总次数（不含切换） --SEIZENBRTCH=TCH占用总次数（含切换） --DROPNBRTCH=TCH掉话总次数 --TCHTRAF=TCH总话务量 --GSMBYTES=GSM流量(MB) --PDCHULBYTES=PDCH上行数据流量（单位:MB） --PDCHDLBYTES=PDCH下行数据流量（单位:MB） --EGPRSDLBYTES=EGPRS下行RLC层流量（单位:MB） --EGPRSULBYTES=EGPRS上行RLC层流量（单位:MB） --ATTNBRHANDOVER=切换请求总次数 --SUCCNBRHANDOVER=切换成功总次数 --SEIZEDNBRSDCCH=SDCCH分配总次数 --SESNBRSDCCH=SDCCH占用总次数 --WIRE_CONN_RATIO=无线接通率(%) --WIRE_INSERT_RATIO=无线接入性 --OVFL_VOICE_RATIO=话音溢出率(%) --OVFL_SIGN_RATIO=信令溢出率(%) --SW_SUCC_RATIO=切换成功率(%) --DROP_RATIO=掉话率(%) --SDCCH_DISTRIBUTE_SUCC_RATIO=SDCCH分配成功率(%) --TCH_DISTRIBUTE_SUCC_RATIO=TCH分配成功率(%) --WIRE_DROP_RATIO=无线掉话率(%) --TCHHALFTRAF=半速率话务量 --TCHHALFTRAF_RATIO=半速率话务量占用比例(%) --AVAILNBRDLTBF=下行平均并发TBF数 --AVAILSEIZENBRPDCH=占用的PDCH的平均数目(含EGPRS和GPRS) --PDCH_REUSABILITY=PDCH复用度 --VOICE_CHANNEL_CNT=语音信道数 --STATIC_CHANNEL_CNT=静态数据信道数 --WIRE_USE_RATIO=无线利用率(%)
</select>

select 
TIME_ID,
CELL_NAME,
BUSY_TIME,
round(VOICE_TRAF,2) VOICE_TRAF,
round(AVAILSEIZENBRPDCH,2) AVAILSEIZENBRPDCH,
VOICE_CHANNEL_CNT,
STATIC_CHANNEL_CNT,
round(WIRE_USE_RATIO,2) WIRE_USE_RATIO,
ATTNBRSDCCH,
ATTNBRTCHNHO,
SEIZENBRTCHNHO,
SEIZENBRTCH,
DROPNBRTCH,
round(TCHTRAF,2) TCHTRAF,
round(GSMBYTES,2) GSMBYTES,
ATTNBRHANDOVER,
SUCCNBRHANDOVER,
SEIZEDNBRSDCCH,
round(WIRE_INSERT_RATIO,2) WIRE_INSERT_RATIO,
round(SW_SUCC_RATIO,2) SW_SUCC_RATIO,
round(WIRE_DROP_RATIO,2) WIRE_DROP_RATIO
from <included id="tableChooseSE"/> where 1=1
<if test=" '@isContinue'=='t' ">
    and TIME_ID between to_number(#startTime#) and to_number(#endTime#)
</if>
<if test=" '@isContinue'=='f' ">
    and to_char(TIME_ID) in (#discteteTime#)
</if> 
<jdbcType name="discteteTime" type="array-char"/>

//TD小区话务利用率
<select id="tableChooseSE">    
     <if test=" '@timeType'=='month' ">IPMSDM.DM_RE_3G_CELL_HW_UTILITY_M</if>
     <if test=" '@timeType'=='hour' ">IPMSDM.DM_RE_3G_CELL_HW_BUSINESS_H</if>
     <if test=" '@timeType'=='day' ">IPMSDM.DM_RE_3G_CELL_HW_UTILITY_D</if>   
</select>


<select id="resultMapping">
 --TIME_ID=时间 --CELL_NAME=小区名称 --SUCCCONNESTAB_1=CS域RRC建立成功次数（业务相关） --ATTCONNESTAB_1=CS域RRC建立尝试次数（业务相关） --SUCCESTABCSPERCELL=CS域RAB建立成功的RAB数目 --ATTESTABCSPERCELL=CS域RAB建立请求的RAB数目 --CS_WIRE_CONN_RATIO=CS域无线接通率(%) --SUCCESTABCSPERCELL_CONV_2_2=语音业务RAB建立成功的RAB数目 --ATTESTABCSPERCELL_CONV_2_2=语音业务RAB建立请求的RAB数目 --SUCCESTABCSPERCELL_2_2_RATIO=语音业务RAB建立成功率(%) --AMR_WIRE_CONN_RATIO=AMR(语音)业务无线接通率(%) --SUCCESTABCSPERCELL_CONV_5_5=视频电话业务RAB建立成功的RAB数目 --ATTESTABCSPERCELL_CONV_5_5=视频电话业务RAB建立请求的RAB数目 --VP_WIRE_CONN_RATIO=视频电视(VP)无线接通率(%) --SUCCCONNESTAB=PS域RRC建立成功次数（业务相关） --ATTCONNESTAB=PS域RRC建立尝试次数（业务相关） --SUCCESTABPSPERCELL=PS域RAB建立成功的RAB数目 --ATTESTABPSPERCELL=PS域RAB建立请求的RAB数目 --PS_WIRE_CONN_RATIO=PS域无线接通率(%) --RELREQCSPERCELL=RNC请求释放的电路域RAB数目 --CS_WIRE_DROP_RATIO=CS域无线掉话率(%) --RELREQCSPERCELL_CONV=RNC请求释放的语音业务RAB总数目 --SUCCESTABCSPERCELL_CONV=语音业务RAB建立成功的RAB 数目 --AMR_WIRE_DROP_RATIO=AMR(语音)业务无线掉话率(%) --RELREQCSPERCELL_CONV_5_5=RNC请求释放的视频电话业务RAB 总数目 --VP_WIRE_DROP_RATIO=视频电视(VP)无线掉话率(%) --RELREQPSPERCELL=RNC请求释放的PS域RAB总数目 --PS_WIRE_DROP_RATIO=PS域无线掉线率(%) --VOICE_TRAFFIC=语音话务量 --VIDEO_TRAFFIC=视频话务量 --PSULOCT=Ps域上行流量(MB) --PSDLOCT=Ps域下行流量(MB) --PSOCT=PS域总流量(MB) --NBR_AVAILBRUUL=配置的上行BRU数 --NBR_AVAILBRUDL=配置的下行BRU数 --MEAN_NBR_ASSNBRUUL=上行平均占用的BRU数 --MEAN_NBR_ASSNBRUDL=下行平均占用的BRU数 --TD_NETWORK_USE_RATIO=TD网络利用率(%)
</select>

select 
TIME_ID,
CELL_NAME,
SUCCCONNESTAB_1,
ATTCONNESTAB_1,
SUCCESTABCSPERCELL,
ATTESTABCSPERCELL,
round(AMR_WIRE_CONN_RATIO,2) AMR_WIRE_CONN_RATIO,
SUCCCONNESTAB,
ATTCONNESTAB,
SUCCESTABPSPERCELL,
ATTESTABPSPERCELL,
round(PS_WIRE_CONN_RATIO,2) PS_WIRE_CONN_RATIO,
RELREQCSPERCELL_CONV,
SUCCESTABCSPERCELL_CONV,
round(AMR_WIRE_DROP_RATIO,2) AMR_WIRE_DROP_RATIO,
RELREQPSPERCELL,
round(PS_WIRE_DROP_RATIO,2) PS_WIRE_DROP_RATIO,
round(VOICE_TRAFFIC,2) VOICE_TRAFFIC,
round(VIDEO_TRAFFIC,2) VIDEO_TRAFFIC,
round(PSULOCT,2) PSULOCT,
round(PSDLOCT,2) PSDLOCT,
round(PSOCT,2) PSOCT,
NBR_AVAILBRUUL,
NBR_AVAILBRUDL,
round(MEAN_NBR_ASSNBRUUL,2) MEAN_NBR_ASSNBRUUL,
round(MEAN_NBR_ASSNBRUDL,2) MEAN_NBR_ASSNBRUDL,
round(TD_NETWORK_USE_RATIO,2) TD_NETWORK_USE_RATIO
from <included id="tableChooseSE"/> where 1=1
<if test=" '@isContinue'=='t' ">
    and TIME_ID between to_number(#startTime#) and to_number(#endTime#)
</if>
<if test=" '@isContinue'=='f' ">
    and to_char(TIME_ID) in (#discteteTime#)
</if> 
<jdbcType name="discteteTime" type="array-char"/>


//LTE小区话务利用率
<select id="tableChooseSE">    
     <if test=" '@timeType'=='month' ">IPMSDM.DM_RE_4G_CELL_HW_UTILITY_M</if>
     <if test=" '@timeType'=='hour' ">IPMSDM.DM_RE_4G_CELL_HW_BUSINESS_H</if>
     <if test=" '@timeType'=='day' ">IPMSDM.DM_RE_4G_CELL_HW_UTILITY_D</if>   
</select>


<select id="resultMapping">
 --TIME_ID=时间 --CELL_NAME=小区名称 --UPOCTUL=上行流量(MB) --UPOCTDL=下行流量(MB) --UPOCT=上下行总流量(MB) --ATTCONNESTAB=RRC连接建立请求次数 --RRC连接建立请求次数 --SUCCCONNESTAB=RRC连接建立成功次数 --RRC_CONN_SUCC_RATIO=RRC连接建立成功率(%) --NBRATTESTAB=E-RAB建立请求数 --NBRSUCCESTAB=E-RAB建立成功数 --ERAB_ESTAB_SUCC_RATIO=E-RAB建立成功率(%) --WIRE_CONN_RATIO=无线接通率(%) --ATTRELENB=eNB请求释放上下文数 --ATTRELENBNORMAL=正常的eNB请求释放上下文数 --SUCCINITALSETUP=初始上下文建立成功次数 --NBRLEFT_CONTEXT=遗留上下文个数 --WIRE_DROP_RATIO=无线掉线率(%) --NBRREQRELENB=eNB请求释放的E-RAB数 --NBRREQRELENB_NORMAL=正常的eNB请求释放的E-RAB数 --HOFAIL=切出失败的E-RAB数 --NBRLEFT=遗留E-RAB个数 --NBRHOINC=切换入E-RAB数 --ERAB_DROP_RATIO_CL=E-RAB掉线率（小区级）(%) --ERAB_DROP_RATIO=E-RAB掉线率(%) --ATTPREPINC=eNB间切换入请求次数 --SUCCPREPINC=eNB间切换入准备成功次数 --ENB_INTER_SW_IN_PRE_SUCC_RATIO=eNB间切换入准备成功率(%) --ATTOUTINTERENBS1=eNB间S1切换出请求次数 --SUCCOUTINTERENBS1=eNB间S1切换出成功次数 --ENB_INTER_S1_SW_SUCC_RATIO=eNB间S1切换成功率(%) --ATTOUTINTERENBX2=eNB间X2切换出请求次数 --SUCCOUTINTERENBX2=eNB间X2切换出成功次数 --ENB_INTER_X2_SW_SUCC_RATIO=eNB间X2切换成功率(%) --ENB_INTER_SW_SUCC_RATIO=eNB间切换成功率(%) --ATTOUTINTRAENB=eNB内切换出请求次数 --SUCCOUTINTRAENB=eNB内切换出成功次数 --ENB_INTRA_SW_SUCC_RATIO=eNB内切换成功率(%) --SW_SUCC_RATIO=切换成功率(%) --PRBTOTUL=上行PUSCH PRB占用平均数 --PUSCHPRBMEANTOT=上行PUSCH PRB可用平均数 --PRBTOTDL=下行PDSCH PRB占用平均数 --PDSCHPRBMEANTOT=下行PDSCH PRB可用平均数 --MEAN_PRB_UL_UTIL_RATIO=上行PRB平均利用率(%) --MEAN_PRB_DL_UTIL_RATIO=下行PRB平均利用率(%) --PDCCHCCEUTILRATIO=PDCCH信道CCE占用率(%) --CONNMEAN=RRC连接平均数 --CONNMAX=RRC连接最大数 --EFFECTIVECONNMEAN=有效RRC连接平均数 --EFFECTIVECONNMAX=有效RRC连接最大数
</select>

select 
TIME_ID,
CELL_NAME,
round(UPOCTUL,2) UPOCTUL,
round(UPOCTDL,2) UPOCTDL,
round(UPOCT,2) UPOCT,
ATTCONNESTAB,
SUCCCONNESTAB,
round(RRC_CONN_SUCC_RATIO,2) RRC_CONN_SUCC_RATIO,
NBRATTESTAB,
NBRSUCCESTAB,
round(ERAB_ESTAB_SUCC_RATIO,2) ERAB_ESTAB_SUCC_RATIO,
round(WIRE_CONN_RATIO,2) WIRE_CONN_RATIO,
ATTRELENB,
ATTRELENBNORMAL,
SUCCINITALSETUP,
NBRLEFT_CONTEXT,
round(WIRE_DROP_RATIO,2) WIRE_DROP_RATIO,
NBRREQRELENB,
NBRREQRELENB_NORMAL,
HOFAIL,
NBRLEFT,
NBRHOINC,
round(ERAB_DROP_RATIO_CL,2) ERAB_DROP_RATIO_CL,
round(ERAB_DROP_RATIO,2) ERAB_DROP_RATIO,
ATTPREPINC,
SUCCPREPINC,
round(ENB_INTER_SW_IN_PRE_SUCC_RATIO,2) ENB_INTER_SW_IN_PRE_SUCC_RATIO,
ATTOUTINTERENBS1,
SUCCOUTINTERENBS1,
round(ENB_INTER_S1_SW_SUCC_RATIO,2) ENB_INTER_S1_SW_SUCC_RATIO,
ATTOUTINTERENBX2,
SUCCOUTINTERENBX2,
round(ENB_INTER_X2_SW_SUCC_RATIO,2) ENB_INTER_X2_SW_SUCC_RATIO,
round(ENB_INTER_SW_SUCC_RATIO,2) ENB_INTER_SW_SUCC_RATIO,
ATTOUTINTRAENB,
SUCCOUTINTRAENB,
round(ENB_INTRA_SW_SUCC_RATIO,2) ENB_INTRA_SW_SUCC_RATIO,
round(SW_SUCC_RATIO,2) SW_SUCC_RATIO,
round(PRBTOTUL,2) PRBTOTUL,
round(PUSCHPRBMEANTOT,2) PUSCHPRBMEANTOT,
round(PRBTOTDL,2) PRBTOTDL,
round(PDSCHPRBMEANTOT,2) PDSCHPRBMEANTOT,
round(MEAN_PRB_UL_UTIL_RATIO,2) MEAN_PRB_UL_UTIL_RATIO,
round(MEAN_PRB_DL_UTIL_RATIO,2) MEAN_PRB_DL_UTIL_RATIO,
round(PDCCHCCEUTILRATIO,2) PDCCHCCEUTILRATIO,
round(CONNMEAN,2) CONNMEAN,
CONNMAX,
round(EFFECTIVECONNMEAN,2) EFFECTIVECONNMEAN,
EFFECTIVECONNMAX
from <included id="tableChooseSE"/> where 1=1
<if test=" '@isContinue'=='t' ">
    and TIME_ID between to_number(#startTime#) and to_number(#endTime#)
</if>
<if test=" '@isContinue'=='f' ">
    and to_char(TIME_ID) in (#discteteTime#)
</if> 
<jdbcType name="discteteTime" type="array-char"/>